server:
  port: 7001
spring:
  application:
    name: sop-demo-cluster
 # nacos
  cloud:
    nacos:
      discovery:
        enabled: true
        service: ${spring.application.name}
        server-addr: 127.0.0.1:8848