server:
  port: 7002
spring:
  application:
    name: sop-demo-cluster
  profiles:
    active: dev
  # nacos
  cloud:
    nacos:
      discovery:
        enabled: true
        service: ${spring.application.name}
        server-addr: 127.0.0.1:8848
