server:
  port: 9001
spring:
  application:
    name: boot-admin-client
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: ${spring.application.name}
  jmx:
    enabled: true
#  boot:
#    admin:
#      client:
#        url: http://127.0.0.1:8001
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


