server:
  port: 9001
spring:
  application:
    name: boot-client-server
  boot:
    admin:
      client:
        url: http://127.0.0.1:8001
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: info


